name: moleonline-web

services:
    moleonline-web:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        container_name: moleonline-web
        ports:
            - "${MOLEONLINE_PORT:-8080}:8080"
        volumes:
            - ./nginx.devel.conf:/etc/nginx/nginx.conf:ro
        logging:
            driver: journald
            options:
                tag: channelsdb-web
