name: moleonline-web

services:
    moleonline-web:
        ports:
            - "80:8080"
            - "443:8443"
        volumes:
            - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/live/moleonline.biodata.ceitec.cz/fullchain.pem:/etc/fullchain.pem:ro
            - /etc/letsencrypt/live/moleonline.biodata.ceitec.cz/privkey.pem:/etc/privkey.pem:ro
